#!/bin/sh

# used for mac address randomization for VNET jails
__get_next_mac () {
    local _mac_base _mac_offset _calc_mac _mac _mac_postfix

    _mac_base=$(echo "${1}" | tr '[a-z]' '[A-Z]')
    _mac_offset=$(echo "obase=16; ${2}" | bc)

    _calc_mac=$(echo "obase=16; ibase=16; ${_mac_base} + ${_mac_offset}" | bc)
    _mac_postfix=$(echo "${_calc_mac}" | awk '{ print substr($0, length($0)-5, length($0)) }')
    _mac="${mac_prefix}${_mac_postfix}"

    echo "${_mac}"
}

# Generate a new set of mac addresses for epair interfaces
__generate_mac () {
    local _mac_offset _dataset _uuid _mac_base _mac_epair_a _mac_epair_b _mac

    _mac_offset=${1}
    _dataset=${2}

    _uuid=$(__get_dataset_ioc_prop host_hostuuid ${_dataset})
    _mac_base=$(echo ${_uuid} | awk '{ print substr($0, 0, 6) }')
    _mac_epair_a=$(__get_next_mac "${_mac_base}" "${_mac_offset}")
    _mac_epair_b=$(__get_next_mac "${_mac_base}" "${_mac_offset}+1")
    _mac=${_mac_epair_a},${_mac_epair_b}

    echo "${_mac}"
}

# Expects input: _nic _mac_offset _epair_leg _uuid
# outputs a single mac address
# Example: __validate_mac ${_nic} ${_mac_offset} a ${_dataset}
__validate_mac () {
    local _nic _mac_offset _epair_leg _dataset _mac _return

    _nic=${1}
    _mac_offset=${2}
    _epair_leg=${3}
    _dataset=${4}

    _mac=$(__get_dataset_ioc_prop ${_nic}_mac ${_dataset})

    if [ "${_mac}" == "none" ] ; then
        _mac=$(__generate_mac ${_mac_offset} ${_dataset})
        __set_dataset_ioc_prop ${_nic}_mac=${_mac} ${_dataset}
    fi

    if [ "${_epair_leg}" == "a" ] ; then
        _return=${_mac%%,*}
    elif [ "${_epair_leg}" == "b" ] ; then
        _return=${_mac#*,}
    fi

    echo "${_return}"
}

# Expects ${1} for action and ${2} for UUID
__networking () {
    local _action _dataset

    _action=${1}
    _dataset=${2}

    case "${_action}" in
        start) __start_networking ${_dataset};;
        stop) __stop_networking ${_dataset};;
        *) __fatal_error "__networking: Invalid action \"${_action}\"";;
    esac
}

__start_networking () {
    local _dataset _uuid _jid _ip4 _ip6 _defaultgw _defaultgw6 _nics
    local _mac_offset _i _nic _bridge _memberif _brmtu _epair_a _epair_b
    local _mac_epair_a _mac_epair_b _addrs _iface _ip

    _dataset=${1}

    _uuid=$(__get_dataset_ioc_prop host_hostuuid ${_dataset})
    _jid=$(jls -j ioc-${_uuid} jid)
    _ip4=$(__get_dataset_ioc_prop ip4_addr ${_dataset})
    _ip6=$(__get_dataset_ioc_prop ip6_addr ${_dataset})
    _defaultgw=$(__get_dataset_ioc_prop defaultrouter ${_dataset})
    _defaultgw6=$(__get_dataset_ioc_prop defaultrouter6 ${_dataset})
    _nics=$(__get_dataset_ioc_prop interfaces ${_dataset} | tr ',' ' ')
    _mac_offset=0

    for _i in ${_nics} ; do
        _nic=${_i%%:*}
        _bridge=${_i#*:}
        _memberif=$(ifconfig ${_bridge} | awk '/member/ { print $2; exit }')
        _brmtu=$(ifconfig ${_memberif} | awk '{ print $6; exit }')
        _epair_a=$(ifconfig epair create)
        _epair_b="${_epair_a%a}b"
        ifconfig ${_epair_a} name ${_nic}:${_jid} mtu ${_brmtu}
        _mac_epair_a=$(__validate_mac ${_nic} ${_mac_offset} a ${_dataset})
        ifconfig ${_nic}:${_jid} link ${_mac_epair_a}
        ifconfig ${_nic}:${_jid} description "associated with jail: ${_uuid}"
        ifconfig ${_epair_b} vnet ioc-${_uuid}
        jexec ioc-${_uuid} ifconfig ${_epair_b} name ${_nic} mtu ${_brmtu}
        _mac_epair_b=$(__validate_mac ${_nic} ${_mac_offset} b ${_dataset})
        jexec ioc-${_uuid} ifconfig ${_nic} link ${_mac_epair_b}
        ifconfig ${_bridge} addm ${_nic}:${_jid} up
        ifconfig ${_nic}:${_jid} up
        : $((_mac_offset += 2))
    done

    if [ "${_ip4}" != "none" ] ; then
        IFS=','
        _addrs=$(echo ${_ip4})
        unset IFS

        for _i in ${_addrs} ; do
            _iface=${_i%%|*}
            _ip=${_i#*|}
            jexec ioc-${_uuid} ifconfig ${_iface} ${_ip} up
        done
    fi

    if [ "${_ip6}" != "none" ] ; then
        IFS=','
        _addrs=$(echo ${_ip6})
        unset IFS

        for _i in ${_addrs} ; do
            _iface=${_i%%|*}
            _ip=${_i#*|}
            jexec ioc-${_uuid} ifconfig ${_iface} inet6 ${_ip} up
        done
    fi

    if [ "${_defaultgw}" != "none" ] ; then
        jexec ioc-${_uuid} route add default ${_defaultgw} > /dev/null
    fi

    if [ "${_defaultgw6}" != "none" ] ; then
        jexec ioc-${_uuid} route add -6 default ${_defaultgw6} >/dev/null
    fi
}

__sub_default_iface () {
    local _default_iface _addrs

    _default_iface=${1}
    _addrs=${2}

    if [ "${_addrs}" != "none" ] ; then
        echo ${_addrs} | sed -e "s/DEFAULT|/${_default_iface}|/g"
    fi
}

__sub_autoip4 () {
    local _ip4_addr _autoip4 _return

    _ip4_addr=${1}

    # Check if the user wants to use an automatic IP4 address
    echo "${_ip4_addr}" | grep -q "AUTOIP4"
    if [ ${?} -eq 0 ] ; then
        _autoip4=$(__get_autoip4) ||
            __fatal_error "Failed to get automatic IPv4 address."
        _return=$(echo "${_ip4_addr}" | sed "s#AUTOIP4#${_autoip4}#")
    else
        _return=${_ip4_addr}
    fi

    echo ${_return}
}

__get_autoip4 () {
    local _autostart _autoend _autobase _jails _freeip _nextaddr
    local _jail _jip4_prop _jip4_ifaddr _jip4 _autoip

    _autostart=$(__get_default_prop ip4_autostart)
    __require_not_empty "${_autostart}" \
                        "AUTOIP4 is specified, but ip4_autostart is not set!"

    _autoend=$(__get_default_prop ip4_autoend)
    __require_not_empty "${_autoend}" \
                        "AUTOIP4 is specified, but ip4_autoend is not set!"

    _autosubnet=$(__get_default_prop ip4_autosubnet)
    [ "${_autosubnet}" -gt 0 -a "${_autosubnet}" -le 32 ] 2>/dev/null ||
        __fatal_error "Invalid default for ip4_autosubnet: ${_autosubnet}
         Please set a value within the range 0 < ip4_autosubnet <= 32"

    _autobase=$(netstat -f inet -nrW | awk '/^default/ { print $2 }' \
                       | cut -d '.' -f 1-3)
    _jails=$(__find_jail ALL)

    # Now loop through all the jails, and find a free IP we can use
    # that fits within the autostart/autoend ranges
    _autoip=${_autostart}
    while :
    do
        _freeip=1
        _nextaddr="${_autobase}.${_autoip}"
        # Is this address in use?
        for _jail in ${_jails} ; do
            _jip4_prop=$(__get_dataset_ioc_prop ip4_addr ${_jail})
            _jip4_ifaddr=${_jip4_prop%%/*}
            _jip4=${_jip4_ifaddr#*|}
            if [ "${_jip4}" == "${_nextaddr}" ] ; then
                _freeip=0
                break
            fi
        done

        # On to the next entry to try
        if [ ${_freeip} -eq 0 ] ; then
            _autoip=$((_autoip + 1))
            continue
        fi

        # Sanity checks
        [ ${_autoip} -le ${_autoend} ] ||
            __fatal_error "IP4 Automatic Address exhaustion"

        [ ${_autoip} -lt 254 ] ||
            __fatal_error "IP4 Address outside of bounds"

        break
     done

     echo "${_nextaddr}/${_autosubnet}"
}

__stop_networking () {
    local _dataset _uuid _jid _nics _i _nic

    _dataset=${1}
    _uuid=$(__get_dataset_ioc_prop host_hostuuid ${_dataset})
    _jid=$(jls -j ioc-${_uuid} jid)
    _nics=$(__get_dataset_ioc_prop interfaces ${_dataset} | tr ',' ' ')

    for _i in ${_nics} ; do
        _nic=${_i%%:*}
        ifconfig ${_nic}:${_jid} destroy
    done
}

__stop_legacy_networking () {
    local _dataset _ip4_addr_prop _ip6_addr_prop _default_iface
    local _ip4_addr _ip6_addr _addrs _ip _iface _ip4 _ip6

    _dataset=${1}

    _default_iface=$(netstat -f inet -nrW | awk '/^default/ { print $6 }')

    _ip4_addr=$(__get_dataset_ioc_prop ip4_addr ${_dataset})
    if [ "${_ip4_addr}" != "none" ] ; then
        IFS=','
        _addrs=$(echo ${_ip4_addr} | sed "s/DEFAULT|/${_default_iface}|/g")
        unset IFS

        for _ip in ${_addrs} ; do
            _iface=${_ip%%|*}
            _ip4=${_ip#*|}
            ifconfig ${_iface} ${_ip4%%/*} -alias
        done
    fi

    _ip6_addr=$(__get_dataset_ioc_prop ip6_addr ${_dataset})
    if [ "${_ip6_addr}" != "none" ] ; then
        IFS=','
        _addrs=$(echo ${_ip6_addr} | sed "s/DEFAULT|/${_default_iface}|/g")
        unset IFS

        for _ip in ${_addrs} ; do
            _iface=${_ip%%|*}
            _ip6=${_ip#*|}
            ifconfig ${_iface} inet6 ${_ip6%%/*} -alias
        done
    fi
}
