#!/bin/sh

# This is for remote host initialization
# example: iocage init-host IP-ADDRESS
# will set up the host for iocage

__init_host () {
    local _host _pool _ioc _fs_list _remote_pool _fs

    _host=${1}
    __require_not_empty "${_host}" "Missing host name"
    
    _pool=${2}
    __require_not_empty "${_pool}" "Missing pool name"

    _ioc="org.freebsd.iocage"
    
    _fs_list="${iocroot}/base
              ${iocroot}/download
              ${iocroot}/releases
              ${iocroot}/.defaults"

    _remote_pool=$(ssh ${_host} zpool get -Ho value name ${_pool})
    __require_not_empty "${_remote_pool}" "No remote pool ${_pool} found"

    ssh ${_host} "zfs set ${_ioc}:active=yes ${_remote_pool}
               && zfs set ${_ioc}:version='${iocage_version}' ${_remote_pool}
               && zfs create ${_remote_pool}${iocroot}
               && zfs set mountpoint=${iocroot} ${_remote_pool}${iocroot}
               && mkdir ${iocroot}/log"

    for _fs in ${_fs_list} ; do
        zfs snapshot -r ${pool}${_fs}@init
        zfs send -vR ${pool}${_fs}@init | ssh ${_host} "zfs recv ${_remote_pool}${_fs}"
        zfs destroy -r ${pool}${_fs}@init
    done
}
