#!/bin/sh

__start_jail () {
    local _dataset _fulluuid _id _status _template _nics _i _nic _bridge \
          _jail_hostid _tag _jail_type _mountpoint _procfs _jzfs _jzfs_pool \
          _jzfs_dataset _vnet _cpuset _exec_start

    _dataset=${1}

    _fulluuid=$(__get_dataset_ioc_prop host_hostuuid ${_dataset})
    _id="[${_fulluuid}]"
    _status=0

    if __is_running ${_fulluuid} ; then
        echo "${_id} Jail is already up"
        return 0
    fi

    _template=$(__get_dataset_ioc_prop template ${_dataset})
    if [ "${_template}" = "yes" ] ; then
        return 0
    fi

    _nics=$(__get_dataset_ioc_prop interfaces ${_dataset} | tr ',' ' ')
    for _i in ${_nics} ; do
        _nic=${_i%%:*}
        _bridge=${_i#*:}

        if [ -z "${_nic}" ] || [ -z "${_bridge}" ] ; then
            __stderr "${_id} Incorrect interfaces property format"
            return 1
        fi
    done

    _tag=$(__get_dataset_ioc_prop tag ${_dataset})

    echo "${_id} Starting (tag: \"${_tag}\")"

    _jail_type=$(__get_dataset_ioc_prop type ${_dataset})
    if [ "${_jail_type}" = "basejail" ] ; then
        # Re-clone required filesystems
        __reclone_basejail ${_dataset}
    fi

    __update_mountpoint ${_dataset}
    _mountpoint=$(__get_dataset_zfs_prop mountpoint ${_dataset})

    mkdir -p /tmp/iocage

    sed -e "s|%jailroot%|${_mountpoint}/root|g" < ${_mountpoint}/fstab \
        > /tmp/iocage/fstab.${_fulluuid}

    _procfs=$(__get_dataset_ioc_prop mount_procfs ${_dataset})
    if [ "${_procfs}" -eq 1 ] ; then
        mount -t procfs proc ${_mountpoint}/root/proc
    fi

    _jzfs=$(__get_dataset_ioc_prop jail_zfs ${_dataset})
    if [ "${_jzfs}" = "on" ] ; then
        _jzfs_dataset=$(__get_dataset_ioc_prop jail_zfs_dataset ${_dataset})
        _jzfs_pool=$(__get_dataset_ioc_prop jail_zfs_pool ${_dataset})
        if [ $(__wc ${_jzfs_pool}) -ne 1 ] ; then
            __stderr "${_id} Invalid jail_zfs_pool: ${_jzfs_pool}"
            return 1
        fi
        if [ "${_jzfs_pool}" = "DEFAULT" ] ; then
            _jzfs_pool=${pool}
        fi
        __set_dataset_ioc_prop allow_mount=1 ${_dataset}
        __set_dataset_ioc_prop enforce_statfs=1 ${_dataset}
        __set_dataset_ioc_prop allow_mount_zfs=1 ${_dataset}
        __set_dataset_zfs_prop jailed=on ${_jzfs_pool}/${_jzfs_dataset}
    fi

    echo -e "${_id} Filesystems preparation ${OK}"

    _vnet=$(__get_dataset_ioc_prop vnet ${_dataset})
    if [ "${_vnet}" = "on" -o "${_vnet}" = "-" ] ; then
        if [ -n $(sysctl -qn kern.features.vimage) ] ; then
            __vnet_start ${_dataset}
            if [ ${?} -eq 0 ] ; then
                echo -e "${_id} Starting jail (VNET mode) ${OK}"
            else
                __stderr -e "${_id} Starting jail (VNET mode) ${FAILED}"
                return 1
            fi

            __networking start ${_dataset}
            if [ ${?} -eq 0 ] ; then
                echo -e "${_id} VNET configuration ${OK}"
            else
                __stderr -e "${_id} VNET configuration ${FAILED}"
                _status=1
            fi
        else
            __stderr "${_id} Start failed:"
            __stderr "${_id}   vnet=on but kernel is not VNET capable!"
            __stderr "${_id}   Turn vnet off for this jail or recompile"
            __stderr "${_id}   kernel with VNET."
            return 1
        fi
    else
        __legacy_start ${_dataset}
        if [ ${?} -eq 0 ] ; then
            echo -e "${_id} Starting jail (shared IP mode) ${OK}"
        else
            __stderr -e "${_id} Starting jail (shared IP mode) ${FAILED}"
            return 1
        fi
    fi

    cd ${_mountpoint}/root/dev && ln -s ../var/run/log log

    __rctl_limits ${_dataset}

    _cpuset=$(__get_dataset_ioc_prop cpuset ${_dataset})
    if [ "${_cpuset}" != "off" ] ; then
        _jid=$(jls -j ioc-${_fulluuid} jid)
        cpuset -l ${_cpuset} -j ${_jid}
        if [ ${?} -eq 0 ] ; then
            echo -e "${_id} Setting CPU affinity ${OK}"
        else
            __stderr -e "${_id} Setting CPU affinity ${FAILED}"
            _status=1
        fi
    fi

    if [ "${_jzfs}" = "on" ] ; then
        zfs jail ioc-${_fulluuid} ${_jzfs_pool}/${_jzfs_dataset}
    fi

    __resolv_conf ${_dataset}

    _exec_start=$(__get_dataset_ioc_prop exec_start ${_dataset})
    __exec ${_dataset} ${_exec_start} \
        >> ${iocroot}/log/${_fulluuid}-console.log 2>&1
    if [ ${?} -eq 0 ] ; then
        echo -e "${_id} Starting services ${OK}"
    else
        __stderr -e "${_id} Starting services ${FAILED}"
        _status=1
    fi

    __set_dataset_ioc_prop last_started=$(date "+%F_%T") ${_dataset}

    return ${_status}
}

# Start a VNET jail
__vnet_start () {
    local _dataset _uuid _mountpoint _tmpfs _fdescfs

    _dataset=${1}

    _uuid=$(__get_dataset_ioc_prop host_hostuuid ${_dataset})
    _mountpoint=$(__get_dataset_zfs_prop mountpoint ${_dataset})

    if [ "$(uname -U)" = "903000" ] ; then
      _tmpfs=""
      _fdescfs=""
    else
      _tmpfs="allow.mount.tmpfs=$(__get_dataset_ioc_prop allow_mount_tmpfs \
                                                         ${_dataset})"
      _fdescfs="mount.fdescfs=$(__get_dataset_ioc_prop mount_fdescfs \
                                                       ${_dataset})"
    fi

    jail -c vnet \
         name="ioc-${_uuid}" \
         host.hostname="$(__get_dataset_ioc_prop host_hostname ${_dataset})" \
         path="${_mountpoint}/root" \
         securelevel="$(__get_dataset_ioc_prop securelevel ${_dataset})" \
         host.hostuuid="${_uuid}" \
         devfs_ruleset="$(__get_dataset_ioc_prop devfs_ruleset ${_dataset})" \
         enforce_statfs="$(__get_dataset_ioc_prop enforce_statfs ${_dataset})" \
         children.max="$(__get_dataset_ioc_prop children_max ${_dataset})" \
         allow.set_hostname="$(__get_dataset_ioc_prop allow_set_hostname \
                                                      ${_dataset})" \
         allow.sysvipc="$(__get_dataset_ioc_prop allow_sysvipc \
                                                 ${_dataset})" \
         allow.raw_sockets="$(__get_dataset_ioc_prop allow_raw_sockets \
                                                     ${_dataset})" \
         allow.chflags="$(__get_dataset_ioc_prop allow_chflags ${_dataset})" \
         allow.mount="$(__get_dataset_ioc_prop allow_mount ${_dataset})" \
         allow.mount.devfs="$(__get_dataset_ioc_prop allow_mount_devfs \
                                                     ${_dataset})" \
         allow.mount.nullfs="$(__get_dataset_ioc_prop allow_mount_nullfs \
                                                      ${_dataset})" \
         allow.mount.procfs="$(__get_dataset_ioc_prop allow_mount_procfs \
                                                      ${_dataset})" \
         "${_tmpfs}" \
         allow.mount.zfs="$(__get_dataset_ioc_prop allow_mount_zfs \
                                                   ${_dataset})" \
         allow.quotas="$(__get_dataset_ioc_prop allow_quotas ${_dataset})" \
         allow.socket_af="$(__get_dataset_ioc_prop allow_socket_af \
                                                   ${_dataset})" \
         exec.fib="$(__get_dataset_ioc_prop exec_fib ${_dataset})" \
         exec.prestart="$(__findscript ${_dataset} prestart)" \
         exec.poststart="$(__findscript ${_dataset} poststart)" \
         exec.prestop="$(__findscript ${_dataset} prestop)" \
         exec.stop="$(__get_dataset_ioc_prop exec_stop ${_dataset})" \
         exec.clean="$(__get_dataset_ioc_prop exec_clean ${_dataset})" \
         exec.timeout="$(__get_dataset_ioc_prop exec_timeout ${_dataset})" \
         stop.timeout="$(__get_dataset_ioc_prop stop_timeout ${_dataset})" \
         mount.fstab="/tmp/iocage/fstab.${_uuid}" \
         mount.devfs="$(__get_dataset_ioc_prop mount_devfs ${_dataset})" \
         "${_fdescfs}" \
         allow.dying \
         exec.consolelog="${iocroot}/log/${_uuid}-console.log" \
         persist
}

# Start a shared IP jail
__legacy_start () {
    local _dataset _uuid _mountpoint _ip4_addr_prop _ip6_addr_prop \
          _autoip4 _default_iface _ip4_addr _ip6_addr _ip4 _ip6 \
          _ip4_addr_propline _ip6_addr_propline _fdescfs _tmpfs _ip6_addrsel

    _dataset=${1}

    _uuid=$(__get_dataset_ioc_prop host_hostuuid ${_dataset})
    _mountpoint=$(__get_dataset_zfs_prop mountpoint ${_dataset})
    _ip4_addr_prop=$(__get_dataset_ioc_prop ip4_addr ${_dataset})
    _ip6_addr_prop=$(__get_dataset_ioc_prop ip6_addr ${_dataset})

    # Replace DEFAULT with the actual default interface name if needed
    _default_iface=$(netstat -f inet -nrW | awk '/^default/ { print $6 }')
    _ip4_addr=$(__sub_default_iface ${_default_iface} "${_ip4_addr_prop}")
    _ip6_addr=$(__sub_default_iface ${_default_iface} "${_ip6_addr_prop}")

    _ip4=$(__get_dataset_ioc_prop ip4 ${_dataset})

    # This is mostly a temporary workaround for
    # https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=196474
    if [ "${_ip4}" = "inherit" ] ; then
        _ip4="inherit"
        _ip6="inherit"
        _ip4_addr_propline=""
        _ip6_addr_propline=""
    else
        _ip6=$(__get_dataset_ioc_prop ip6 ${_dataset})
        _ip4_addr_propline="ip4.addr=${_ip4_addr}"
        _ip6_addr_propline="ip6.addr=${_ip6_addr}"
    fi

    if [ "$(uname -U)" = "903000" ];
    then
      _fdescfs=""
      _tmpfs=""
    else
        _fdescfs="mount.fdescfs=$(__get_dataset_ioc_prop mount_fdescfs \
                                                         ${_dataset})"
        _tmpfs="allow.mount.tmpfs=$(__get_dataset_ioc_prop allow_mount_tmpfs \
                                                           ${_dataset})"
    fi

    if [ "${ipv6}" = "on" ] ; then
        _ip6_addrsel=$(__get_dataset_ioc_prop ip6_saddrsel ${_dataset})
        _ip6_props="${_ip6_addr_propline} \
                    ip6.saddrsel=${_ip6_addrsel} \
                    ip6=${_ip6}"
    else
        _ip6_props=""
    fi

    jail -c \
         ${_ip4_addr_propline} \
         ip4.saddrsel="$(__get_dataset_ioc_prop ip4_saddrsel ${_dataset})" \
         ip4="${_ip4}" \
         ${_ip6_props} \
         name="ioc-${_uuid}" \
         host.hostname="$(__get_dataset_ioc_prop host_hostname ${_dataset})" \
         path="${_mountpoint}/root" \
         securelevel="$(__get_dataset_ioc_prop securelevel ${_dataset})" \
         host.hostuuid="${_uuid}" \
         devfs_ruleset="$(__get_dataset_ioc_prop devfs_ruleset ${_dataset})" \
         enforce_statfs="$(__get_dataset_ioc_prop enforce_statfs ${_dataset})" \
         children.max="$(__get_dataset_ioc_prop children_max ${_dataset})" \
         allow.set_hostname="$(__get_dataset_ioc_prop allow_set_hostname \
                                                      ${_dataset})" \
         allow.sysvipc="$(__get_dataset_ioc_prop allow_sysvipc ${_dataset})" \
         allow.raw_sockets="$(__get_dataset_ioc_prop allow_raw_sockets \
                                                     ${_dataset})" \
         allow.chflags="$(__get_dataset_ioc_prop allow_chflags ${_dataset})" \
         allow.mount="$(__get_dataset_ioc_prop allow_mount ${_dataset})" \
         allow.mount.devfs="$(__get_dataset_ioc_prop allow_mount_devfs \
                                                     ${_dataset})" \
         allow.mount.nullfs="$(__get_dataset_ioc_prop allow_mount_nullfs \
                                                      ${_dataset})" \
         allow.mount.procfs="$(__get_dataset_ioc_prop allow_mount_procfs \
                                                      ${_dataset})" \
         "${_tmpfs}" \
         allow.mount.zfs="$(__get_dataset_ioc_prop allow_mount_zfs \
                                                   ${_dataset})" \
         allow.quotas="$(__get_dataset_ioc_prop allow_quotas ${_dataset})" \
         allow.socket_af="$(__get_dataset_ioc_prop allow_socket_af \
                                                   ${_dataset})" \
         exec.fib="$(__get_dataset_ioc_prop exec_fib ${_dataset})" \
         exec.prestart="$(__findscript ${_dataset} prestart)" \
         exec.poststart="$(__findscript ${_dataset} poststart)" \
         exec.prestop="$(__findscript ${_dataset} prestop)" \
         exec.stop="$(__get_dataset_ioc_prop exec_stop ${_dataset})" \
         exec.clean="$(__get_dataset_ioc_prop exec_clean ${_dataset})" \
         exec.timeout="$(__get_dataset_ioc_prop exec_timeout ${_dataset})" \
         stop.timeout="$(__get_dataset_ioc_prop stop_timeout ${_dataset})" \
         mount.fstab="/tmp/iocage/fstab.${_uuid}" \
         mount.devfs="$(__get_dataset_ioc_prop mount_devfs ${_dataset})" \
         "${_fdescfs}" \
         allow.dying \
         exec.consolelog="${iocroot}/log/${_uuid}-console.log" \
         persist
}

__stop_jail () {
    local _dataset _fulluuid _id _status _tag _exec_prestop _exec_stop _vnet \
          _ip4 _exec_poststop _mountpoint _rlimits

    _dataset=${1}

    _fulluuid=$(__get_dataset_ioc_prop host_hostuuid ${_dataset})
    _id="[${_fulluuid}]"
    _status=0

    if ! __is_running ${_fulluuid} ; then
        echo "${_id} Jail is already down"
        return 0
    fi

    _tag=$(__get_dataset_ioc_prop tag ${_dataset})
    _exec_prestop=$(__findscript ${_dataset} prestop)

    echo "${_id} Stopping (tag: \"${_tag}\")"

    eval "${_exec_prestop}"
    if [ ${?} -eq 0 ] ; then
        echo -e "${_id} Running pre-stop ${OK}"
    else
        __stderr -e "${_id} Running pre-stop ${FAILED}"
        _status=1
    fi

    _exec_stop=$(__get_dataset_ioc_prop exec_stop ${_dataset})
    __exec ${_dataset} ${_exec_stop} \
        >> ${iocroot}/log/${_fulluuid}-console.log 2>&1
    if [ ${?} -eq 0 ] ; then
        echo -e "${_id} Stopping services ${OK}"
    else
        __stderr -e "${_id} Stopping services ${FAILED}"
        _status=1
    fi

    _vnet=$(__get_dataset_ioc_prop vnet ${_dataset})

    if [ "${_vnet}" = "on" ] ; then
        __networking stop ${_dataset}
        if [ ${?} -eq 0 ] ; then
            echo -e "${_id} Tearing down VNET ${OK}"
        else
            __stderr -e "${_id} Tearing down VNET ${FAILED}"
            _status=1
        fi
    else
        _ip4=$(__get_dataset_ioc_prop ip4 ${_dataset})

        # don't try to tear down networking if we have "inherit" set
        if [ "${_ip4}" != "inherit" ] ; then
            __stop_legacy_networking ${_dataset}
            if [ ${?} -eq 0 ] ; then
                echo -e "${_id} Stopping legacy networking ${OK}"
            else
                __stderr -e "${_id} Stopping legacy networking ${FAILED}"
                _status=1
            fi
        fi
    fi

    jail -r ioc-${_fulluuid}
    if [ ${?} -eq 0 ] ; then
        echo -e "${_id} Removing jail processes ${OK}"
    else
        __stderr -e "${_id} Removing jail processes ${FAILED}"
        _status=1
    fi

    _exec_poststop=$(__findscript ${_dataset} poststop)

    eval "${_exec_poststop}"
    if [ ${?} -eq 0 ] ; then
        echo -e "${_id} Running post-stop ${OK}"
    else
        __stderr -e "${_id} Running post-stop ${FAILED}"
        _status=1
    fi

    _mountpoint=$(__get_dataset_zfs_prop mountpoint ${_dataset})

    umount -afvF /tmp/iocage/fstab.${_fulluuid} > /dev/null 2>&1
    umount ${_mountpoint}/root/dev/fd > /dev/null 2>&1
    umount ${_mountpoint}/root/dev    > /dev/null 2>&1
    umount ${_mountpoint}/root/proc   > /dev/null 2>&1

    if [ -d ${iocroot}/jails/${_fulluuid}/recorded ] ; then
        umount -ft unionfs ${iocroot}/jails/${_fulluuid}/root > /dev/null 2>&1
    fi

    echo -e "${_id} Unmounting filesystems ${OK}"

    if [ -n $(sysctl -qn kern.features.rctl) ] ; then
        _rlimits=$(rctl | grep -c ${_fulluuid})
        if [ "${_rlimits}" -gt 0 ] ; then
            rctl -r jail:ioc-${_fulluuid}
        fi
    fi

    return ${_status}
}

# Soft restart
__soft_restart_jail () {
    local _dataset _fulluuid _id _exec_stop _exec_start _jid _tag _date

    _dataset=${1}

    _fulluuid=$(__get_dataset_ioc_prop host_hostuuid ${_dataset})
    _id="[${_fulluuid}]"
    _exec_stop=$(__get_dataset_ioc_prop exec_stop ${_dataset})
    _tag=$(__get_dataset_ioc_prop tag ${_dataset})

    echo "${_id} Soft restarting (tag: \"${_tag}\")"

    __exec ${_dataset} ${_exec_stop} \
        >> ${iocroot}/log/${_fulluuid}-console.log 2>&1
    [ ${?} -eq 0 ] ||
        __fatal_error "Soft restart failed."

    _jid=$(jls -j ioc-${_fulluuid} jid)
    _exec_start=$(__get_dataset_ioc_prop exec_start ${_dataset})
    _date=$(date "+%F_%T")

    pkill -j ${_jid}
    __exec ${_dataset} ${_exec_start} \
        >> ${iocroot}/log/${_fulluuid}-console.log 2>&1
    __set_dataset_ioc_prop last_started=${_date} ${_dataset}
}

# Hard restart
__hard_restart_jail () {
    local _dataset

    _dataset=${1}

    __stop_jail ${_dataset}
    __start_jail ${_dataset}
}

__rc_jails () {
    local _action _jails _boot_list _jail _boot _priority _previous_priority \
          _boot_order _i _dataset _uuid _shutdown_order

    _action=${1}
    _jails=$(__find_jail ALL)
    _boot_list=""

    for _jail in ${_jails} ; do
        _boot=$(__get_dataset_ioc_prop boot ${_jail})

        if [ "${_boot}" = "on" ] ; then
            _priority=$(__get_dataset_ioc_prop priority ${_jail})
            _boot_list="${_boot_list}
                        ${_priority},${_jail}"
        fi
    done

    [ -n "${_boot_list}" ] ||
        __fatal_error "None of the jails have boot on."

    _previous_priority=0

    if [ "${_action}" = "boot" ] ; then
        _boot_order=$(echo "${_boot_list}" | awk NF | sort -nb)

        echo "* [I|O|C] booting jails... "

        for _i in ${_boot_order} ; do
            _priority=${_i%%,*}
            _dataset=${_i#*,}
            _uuid=${_dataset##*/}

            if [ ${_priority} -ne ${_previous_priority} ] ; then
                wait
            fi

            if ! __is_running ${_uuid} ; then
                __start_jail ${_dataset} &
            fi

            _previous_priority=${_priority}
        done

    elif [ "${_action}" = "shutdown" ] ; then
        _shutdown_order=$(echo "${_boot_list}" | awk NF | sort -rnb)

        echo "* [I|O|C] shutting down jails... "

        for _i in ${_shutdown_order} ; do
            _priority=${_i%%,*}
            _dataset=${_i#*,}
            _uuid=${_dataset##*/}

            if [ ${_priority} -ne ${_previous_priority} ] ; then
                wait
            fi

            if __is_running ${_uuid} ; then
                __stop_jail ${_dataset} &
            fi

            _previous_priority=${_priority}
        done

    fi

    wait
}
